### PR TITLE
Architect docs

### PR DESCRIPTION
**Pull request by mathi123**
Update architect module with screenshots,

travis build on fork has succeeded here:
https://travis-ci.org/mathi123/vertical-construction

### CODE REVIEW

**Comment by max3903** [comment]
Not sure you want your customer logo in the screenshot

**Comment by mathi123** [comment]
No need for that indeed :-)

**Comment by max3903** [comment]
:+1: 

You can also add your screenshots in the `images` keyword of `__openerp__.py`

**Comment by JosDeGraeve** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
