### PR TITLE
[ADD] base - architect module

### PR DESCRIPTION
**Pull request by mathi123**
Identify a partner as an Architect.

### CODE REVIEW

**Comment by max3903** [comment]
Can you please include the travis and oca_dependencies files as well ?

**Comment by mathi123** [comment]
@max3903 Where can I find a default travis.yml template? Not sure what oca_dependency files are also..

**Comment by max3903** [comment]
Right here:
https://github.com/OCA/maintainer-quality-tools/tree/master/sample_files

**Comment by pedrobaeza** [comment]
Why this has been merged so soon?

There are some things I would like to comment.

**Comment by max3903** [comment]
@mathi123 Please have a look at the conventions:
https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.rst#review

You should wait for 2 reviews and 5 days before merging.

**Comment by pedrobaeza** [comment]
Please revert and make again the PR.

**Comment by mathi123** [comment]
Sorry :)
I did that to make my other branches succeed in runbot. If they depend on this module, will they fail?

**Comment by pedrobaeza** [comment]
You can make that your other branches includes these commits and the extra ones, making the "git checkout -b" from this branch instead on the official one.

**Pull request merged**
